# プレミアリーグ
Team.create(league_category_id: 1, name: 'マンチェスター・シティ')
Team.create(league_category_id: 1, name: 'リバプール')
Team.create(league_category_id: 1, name: 'チェルシー')
Team.create(league_category_id: 1, name: 'トッテナム・ホットスパー')
Team.create(league_category_id: 1, name: 'アーセナル')
Team.create(league_category_id: 1, name: 'マンチェスター・ユナイテッド')
Team.create(league_category_id: 1, name: 'ウェストハム・ユナイテッド')
Team.create(league_category_id: 1, name: 'レスター・シティ')
Team.create(league_category_id: 1, name: 'ブライトン')
Team.create(league_category_id: 1, name: 'ウォルバーハンプトン')
Team.create(league_category_id: 1, name: 'ニューカッスル・ユナイテッド')
Team.create(league_category_id: 1, name: 'クリスタル・パレス')
Team.create(league_category_id: 1, name: 'ブレントフォード')
Team.create(league_category_id: 1, name: 'アストン・ビラ')
Team.create(league_category_id: 1, name: 'サウサンプトン')
Team.create(league_category_id: 1, name: 'エバートン')
Team.create(league_category_id: 1, name: 'リーズ・ユナイテッド')
Team.create(league_category_id: 1, name: 'フラム')
Team.create(league_category_id: 1, name: 'ボーンマス')
Team.create(league_category_id: 1, name: 'ノッティンガム・フォレスト')

# ラ・リーガ
Team.create(league_category_id: 2, name: 'レアル・マドリードCF')
Team.create(league_category_id: 2, name: 'FCバルセロナ')
Team.create(league_category_id: 2, name: 'アトレティコ・マドリード')
Team.create(league_category_id: 2, name: 'セビージャFC')
Team.create(league_category_id: 2, name: 'レアル・ベティス')
Team.create(league_category_id: 2, name: 'レアル・ソシエダ')
Team.create(league_category_id: 2, name: 'ビジャレアルCF')
Team.create(league_category_id: 2, name: 'アトレティック・クルブ')
Team.create(league_category_id: 2, name: 'バレンシアCF')
Team.create(league_category_id: 2, name: 'CAオサスナ')
Team.create(league_category_id: 2, name: 'セルタ・デ・ビーゴ')
Team.create(league_category_id: 2, name: 'ラージョ・バジェカーノ')
Team.create(league_category_id: 2, name: 'エルチェCF')
Team.create(league_category_id: 2, name: 'エスパニョール')
Team.create(league_category_id: 2, name: 'ヘタフェCF')
Team.create(league_category_id: 2, name: 'マジョルカ')
Team.create(league_category_id: 2, name: 'カディスCF')
Team.create(league_category_id: 2, name: 'UDアルメリア')
Team.create(league_category_id: 2, name: 'レアル・バジャドリードCF')
Team.create(league_category_id: 2, name: 'ジローナFC')

# ブンデスリーガ
Team.create(league_category_id: 3, name: 'バイエルン・ミュンヘン')
Team.create(league_category_id: 3, name: 'ボルシア・ドルトムント')
Team.create(league_category_id: 3, name: 'バイエル・レバークーゼン')
Team.create(league_category_id: 3, name: 'RBライプツィヒ')
Team.create(league_category_id: 3, name: '1.FCウニオン・ベルリン')
Team.create(league_category_id: 3, name: 'SCフライブルク')
Team.create(league_category_id: 3, name: '1.FCケルン')
Team.create(league_category_id: 3, name: '1.FSVマインツ05')
Team.create(league_category_id: 3, name: 'TSG1899ホッフェンハイム')
Team.create(league_category_id: 3, name: 'ボルシアMG')
Team.create(league_category_id: 3, name: 'アイントラハト・フランクフルト')
Team.create(league_category_id: 3, name: 'VfLヴォルフスブルク')
Team.create(league_category_id: 3, name: 'VfL ボーフム')
Team.create(league_category_id: 3, name: 'アウグスブルク')
Team.create(league_category_id: 3, name: 'VfBシュトゥットガルト')
Team.create(league_category_id: 3, name: 'ヘルタ・ベルリン')
Team.create(league_category_id: 3, name: 'シャルケ04')
Team.create(league_category_id: 3, name: 'ヴェルダー・ブレーメン')

# セリエA
Team.create(league_category_id: 4, name: 'ACミラン')
Team.create(league_category_id: 4, name: 'インテル・ミラノ')
Team.create(league_category_id: 4, name: 'ナポリ')
Team.create(league_category_id: 4, name: 'ユベントス')
Team.create(league_category_id: 4, name: 'ラツィオ')
Team.create(league_category_id: 4, name: 'ASローマ')
Team.create(league_category_id: 4, name: 'フィオレンティーナ')
Team.create(league_category_id: 4, name: 'アタランタ')
Team.create(league_category_id: 4, name: 'エラス・ヴェローナ')
Team.create(league_category_id: 4, name: 'トリノ')
Team.create(league_category_id: 4, name: 'サッスオーロ')
Team.create(league_category_id: 4, name: 'ウディネーゼ')
Team.create(league_category_id: 4, name: 'ボローニャ')
Team.create(league_category_id: 4, name: 'エンポリ')
Team.create(league_category_id: 4, name: 'サンプドリア')
Team.create(league_category_id: 4, name: 'スペツィア')
Team.create(league_category_id: 4, name: 'サレルニターナ')
Team.create(league_category_id: 4, name: 'レッチェ')
Team.create(league_category_id: 4, name: 'クレモネーゼ')
Team.create(league_category_id: 4, name: 'モンツァ')

# リーグ・アン
Team.create(league_category_id: 5, name: 'パリサンジェルマン')
Team.create(league_category_id: 5, name: 'オリンピック・マルセイユ')
Team.create(league_category_id: 5, name: 'ASモナコ')
Team.create(league_category_id: 5, name: 'スタッド・レンヌ')
Team.create(league_category_id: 5, name: 'OGCニース')
Team.create(league_category_id: 5, name: 'RCストラスブール')
Team.create(league_category_id: 5, name: 'RCランス')
Team.create(league_category_id: 5, name: 'オリンピック・リヨン')
Team.create(league_category_id: 5, name: 'FCナント')
Team.create(league_category_id: 5, name: 'LOSCリール')
Team.create(league_category_id: 5, name: 'スタッド・ブレスト29')
Team.create(league_category_id: 5, name: 'スタッド・ランス')
Team.create(league_category_id: 5, name: 'モンペリエHSC')
Team.create(league_category_id: 5, name: 'アンジェSCO')
Team.create(league_category_id: 5, name: 'トロワAC')
Team.create(league_category_id: 5, name: 'FCロリアン')
Team.create(league_category_id: 5, name: 'クレルモン・フット')
Team.create(league_category_id: 5, name: 'トゥールーズFC')
Team.create(league_category_id: 5, name: 'ACアジャクシオ')
Team.create(league_category_id: 5, name: 'AJオセール')
