meta:
  site: league highlight
  title: league highlight - プレミアリーグハイライト
  description:  ー 世界最高峰のサッカーリーグ、プレミアリーグのハイライトをまとめたサイトです。最新のハイライトをお届けします。
  keywords:
    - サッカー
    - プレミアリーグ
    - イングランド
    - ハイライト
    - スポーツ
  og:
    type: website
    image_path: ogp.png